import { Category, NotificationItem, Priority, User, DocResource, ForumPost } from './types';

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  // 1. 综合管理通知
  {
    id: 'gen-001',
    category: Category.GENERAL,
    title: '【重要】关于2024年度设计评审会的通知',
    department: '研发管理部',
    date: '2024-05-20',
    priority: Priority.HIGH,
    summary: '定于6月15日举行年度设计评审，请各组准备汇报材料。',
    content: '各位同事：\n\n2024年度设计评审会定于6月15日在总部302会议室举行。请各项目组于6月10日前提交详细设计报告及相关图纸。本次评审将重点关注能效优化与成本控制。\n\n研发管理部',
  },
  {
    id: 'gen-002',
    category: Category.GENERAL,
    title: '关于五一劳动节放假及安全检查的通知',
    department: '行政部',
    date: '2024-04-25',
    priority: Priority.MEDIUM,
    summary: '放假时间安排及节前实验室安全隐患排查要求。',
    content: '五一放假安排如下...',
  },
  {
    id: 'gen-003',
    category: Category.GENERAL,
    title: '2024年第一季度绩效考核结果公示',
    department: '人力资源部',
    date: '2024-04-10',
    priority: Priority.LOW,
    summary: '请登录内网查看个人绩效等级。',
    content: '...',
  },
  {
    id: 'gen-004',
    category: Category.GENERAL,
    title: '新版考勤管理制度宣贯会',
    department: '人力资源部',
    date: '2024-03-15',
    priority: Priority.MEDIUM,
    summary: '周五下午2点，全员参加。',
    content: '...',
  },

  // 2. 离心技术通知
  {
    id: 'cen-001',
    category: Category.CENTRIFUGAL,
    title: '【技术分享】离心压缩机气动优化新方法研讨会',
    department: '离心压缩机室',
    date: '2024-05-18',
    priority: Priority.HIGH,
    summary: '探讨基于机器学习的叶轮气动优化策略。',
    content: '本次研讨会将邀请西交大流体机械研究所专家参与...',
  },
  {
    id: 'cen-002',
    category: Category.CENTRIFUGAL,
    title: 'EG系列压缩机密封改造方案评审',
    department: '离心压缩机室',
    date: '2024-05-12',
    priority: Priority.HIGH,
    summary: '针对近期现场反馈的密封泄漏问题提出改进方案。',
    content: '...',
  },
  {
    id: 'cen-003',
    category: Category.CENTRIFUGAL,
    title: '离心机组防喘振控制逻辑更新说明',
    department: '自控室',
    date: '2024-04-28',
    priority: Priority.MEDIUM,
    summary: 'V2.1版本控制逻辑已上线，请设计人员注意参数配置。',
    content: '...',
  },

  // 3. 轴流透平通知
  {
    id: 'axi-001',
    category: Category.AXIAL,
    title: '【更新】设计规范V3.2版本发布',
    department: '标准化室',
    date: '2024-05-15',
    priority: Priority.HIGH,
    summary: '涉及轴流透平叶片材料选用的新标准。',
    content: '新规范主要调整了高温合金材料的许用应力参数...',
  },
  {
    id: 'axi-002',
    category: Category.AXIAL,
    title: 'TRT机组静叶调节机构故障案例分析',
    department: '轴流透平室',
    date: '2024-05-01',
    priority: Priority.MEDIUM,
    summary: '某钢厂TRT项目现场故障复盘。',
    content: '...',
  },
  {
    id: 'axi-003',
    category: Category.AXIAL,
    title: '轴流压缩机级间冷却器选型指南',
    department: '轴流透平室',
    date: '2024-04-20',
    priority: Priority.LOW,
    summary: '更新供应商列表及选型计算书模板。',
    content: '...',
  },

  // 4. 空分专项通知
  {
    id: 'air-001',
    category: Category.AIR_SEPARATION,
    title: '大型空分装置配套压缩机组项目启动会',
    department: '空分项目部',
    date: '2024-05-22',
    priority: Priority.HIGH,
    summary: '10万等级空分项目正式启动，组建专项攻关组。',
    content: '...',
  },
  {
    id: 'air-002',
    category: Category.AIR_SEPARATION,
    title: '空分流程模拟软件Aspen Plus培训',
    department: '工艺流程室',
    date: '2024-05-10',
    priority: Priority.MEDIUM,
    summary: '为期3天的进阶培训，请相关人员报名。',
    content: '...',
  },
  {
    id: 'air-003',
    category: Category.AIR_SEPARATION,
    title: '关于低温材料低温冲击试验要求的变更',
    department: '材料室',
    date: '2024-04-15',
    priority: Priority.HIGH,
    summary: '严格执行GB/T相关新国标。',
    content: '...',
  },

  // 5. CFD及强度计算通知
  {
    id: 'cfd-001',
    category: Category.CFD,
    title: 'ANSYS Workbench 2024 R1版本升级通知',
    department: '信息中心',
    date: '2024-05-19',
    priority: Priority.MEDIUM,
    summary: '服务器将于本周末进行软件升级，暂停计算服务。',
    content: '...',
  },
  {
    id: 'cfd-002',
    category: Category.CFD,
    title: '高速转子动力学临界转速计算误差分析',
    department: '强度计算室',
    date: '2024-05-05',
    priority: Priority.HIGH,
    summary: '针对柔性转子支撑刚度设置的修正建议。',
    content: '...',
  },
  {
    id: 'cfd-003',
    category: Category.CFD,
    title: '叶轮流场分析网格划分规范（试行）',
    department: '气动计算室',
    date: '2024-04-12',
    priority: Priority.MEDIUM,
    summary: '统一网格质量标准，提高计算收敛性。',
    content: '...',
  },

  // 6. 总成技术通知
  {
    id: 'ass-001',
    category: Category.ASSEMBLY,
    title: '机组底座灌浆工艺改进通知',
    department: '总成室',
    date: '2024-05-14',
    priority: Priority.MEDIUM,
    summary: '解决二次灌浆层开裂问题的新工艺要求。',
    content: '...',
  },
  {
    id: 'ass-002',
    category: Category.ASSEMBLY,
    title: '润滑油站管道布置3D模型审查',
    department: '总成室',
    date: '2024-05-08',
    priority: Priority.LOW,
    summary: '请各相关专业会签油站布置图。',
    content: '...',
  },
  {
    id: 'ass-003',
    category: Category.ASSEMBLY,
    title: '关于外购件联轴器护罩的通用化设计',
    department: '标准化室',
    date: '2024-04-05',
    priority: Priority.LOW,
    summary: '减少非标设计，降低采购成本。',
    content: '...',
  },
];

export const MOCK_USERS: User[] = [
  { id: '1', name: '张工', department: '离心室', role: '高级工程师', email: 'zhang@shaangu.com', status: 'Active' },
  { id: '2', name: '李工', department: '轴流室', role: '工程师', email: 'li@shaangu.com', status: 'Active' },
  { id: '3', name: '王经理', department: '研发部', role: '部门经理', email: 'wang@shaangu.com', status: 'Active' },
  { id: '4', name: '赵助理', department: '行政部', role: '助理', email: 'zhao@shaangu.com', status: 'Inactive' },
];

export const MOCK_DOCS: DocResource[] = [
  { id: 'd1', title: 'GB/T 1234-2023 离心压缩机技术条件', type: 'PDF', size: '2.4MB', date: '2024-01-10', downloads: 1250 },
  { id: 'd2', title: 'TRT机组操作维护手册 V4.0', type: 'DOC', size: '15.2MB', date: '2023-11-05', downloads: 890 },
  { id: 'd3', title: '2024年度研发项目申报表', type: 'XLS', size: '45KB', date: '2024-02-20', downloads: 450 },
  { id: 'd4', title: 'ANSYS Fluent 仿真案例集', type: 'PDF', size: '128MB', date: '2023-12-15', downloads: 3200 },
];

export const MOCK_FORUM_POSTS: ForumPost[] = [
  { id: 'f1', title: '关于高转速下轴承油膜振荡的抑制方法探讨', author: '张工', replies: 45, views: 1205, tag: '技术讨论', isHot: true },
  { id: 'f2', title: '求助：ASPEN物性参数库缺失怎么解决？', author: '新员工小刘', replies: 12, views: 340, tag: '问题求助' },
  { id: 'f3', title: '分享几个好用的SolidWorks宏命令', author: '李工', replies: 28, views: 890, tag: '经验分享' },
];
